uint8 PICK_AND_PLACE_FIXED=1
uint8 MOVE_HOME=2
uint8 MOVE_OBSERVE=3
uint8 PICK_AND_PLACE_LATEST_TARGET=4
uint8 CLASSIFY_PLATFORM_TO_COLOR_BOXES=5
uint8 REPEAT_VISUAL_PICK_TO_PAYLOAD=6
uint8 START_FLAME_TRACKING=7
uint8 STOP_FLAME_TRACKING=8

uint8 STAGE_IDLE=0
uint8 STAGE_MOVING_HOME=1
uint8 STAGE_MOVING_PREGRASP=2
uint8 STAGE_MOVING_GRASP=3
uint8 STAGE_CLOSING_GRIPPER=4
uint8 STAGE_LIFTING=5
uint8 STAGE_MOVING_PLACE=6
uint8 STAGE_OPENING_GRIPPER=7
uint8 STAGE_DONE=8
uint8 STAGE_FAILED=9
uint8 STAGE_WAITING_FOR_TARGET=10

uint8 task_type
---
int32 ERROR_NONE=0
int32 ERROR_NOT_READY=1
int32 ERROR_INVALID_TASK=2
int32 ERROR_PLAN_FAILED=3
int32 ERROR_EXECUTION_FAILED=4
int32 ERROR_TIMEOUT=5
int32 ERROR_CANCELED=6

bool success
uint8 stage_reached
int32 error_code
string message
---
uint8 current_stage
string message
